// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import LocaleDropdownController from "./locale_dropdown_controller"
application.register("locale-dropdown", LocaleDropdownController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import NoticeBoardController from "./notice_board_controller"
application.register("notice-board", NoticeBoardController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import PostTypeController from "./post_type_controller"
application.register("post-type", PostTypeController)

import TrixEditorController from "./trix_editor_controller"
application.register("trix-editor", TrixEditorController)

import DisplayModeController from "./display_mode_controller"
application.register("display-mode", DisplayModeController)

import PdfViewerController from "./pdf_viewer_controller"
application.register("pdf-viewer", PdfViewerController)