default: &default
  store_options:
    redis_url: <%= ENV.fetch("REDIS_URL") { "redis://dragonfly:6379/1" } %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default
  store_options:
    redis_url: <%= ENV.fetch("REDIS_URL") { "redis://dragonfly:6379/2" } %>
    namespace: test

production:
  <<: *default
  store_options:
    redis_url: <%= ENV.fetch("REDIS_URL") %>
    namespace: production
